config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'reservation/valider', to: 'reservations#valider'
  get 'reservation/confirm', to: 'reservations#create'
  get 'reservations/check', to: 'reservations#show'
  post 'reservations/check', to: 'reservations#show'

  get 'inquiry', to: 'inquiries#new'
  resources :users
  resources :reservations
  resources :inquiries
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :reservations 
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false } 
  validates :password, presence: true, length: { minimum: 6 }                  
  has_secure_password

  def book(reserved_at)
    self.reservations.build(reserved_at: reserved_at)
  end
  
#has_many :reservations do
 #  def this_day(reserved_at)
  #  where(:reserved_at => self.last.reserved_at.beginning_of_day..self.last.reserved_at.end_of_day)
   #end

#  def this_week(reserved_at)
 #   where(:reserved_at => self.last.reserved_at.beginning_of_day..self.last.reserved_at + 7.days.end_of_day)
  #end   

#end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  before_action :correct_user, only: [:show]
  require 'date' 
  require 'active_support/all'
  
  def show
    #@user = User.find(params[:id])
    #binding.pry
    @weeks = ["lun","mar","mer","jeu","ven","sam","dim"]
    @today = Date.current
    #binding.pry
    @reservations_dates = @user.reservations.where("reserved_at >= ?", @today).order('reserved_at ASC').map(&:reserved_at)
    @this_monday = @today - (@today.wday - 1)

      
    if (params[:week] == '1') || (params[:week] == nil)
      @your_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00)
      
    elsif params[:week] == '2'
      @this_monday += 7.days
      @your_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00)
      
    else
      @this_monday += 14.days
      @your_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'Votre inscription a été validée.'
      redirect_to @user
    else
      flash.now[:danger] = "Votre inscription n'a pas été validée."
      render :new
    end
  end
  

  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def reserved_at_params
    params.require(:reservation).permit(:reserved_at)
  end
  
  def correct_user
    @user = User.find(params[:id])
     unless @user == current_user
       redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1 class="text-center">S'inscrire</h1>
<p class="text-center">新規登録</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1">

      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="form-group">
            <%= f.label :name, "Nom d'utilisateur" %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, 'Adresse e-mail' %>
            <%= f.text_field :email, class: 'form-control', type: 'email' %>
          </div>
          <div class="form-group">
            <%= f.label :password, 'Mot de passe' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, 'Confirmation du mot de passe' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
            <%= f.submit "S'inscrire", class: 'btn btn-block btn-default' %>
       
        <% end %>  

  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center">Mon espace</h1>
<% require 'date' %>
<% require 'active_support/all' %>
<p></p>
<div class="user-profile"></div>

  <div class="text-center name">
    <h2><%= @user.name %></h2>
  </div>
  <div class="panel-body">
    <img class="media-object img-rounded img-responsive center-block" src="<%= gravatar_url(@user, { size: 100 }) %>" alt="">
  </div>
<% #binding.pry %>
<% if  @reservations_dates.count == 1 %>
  <p class="text-center">Votre prochain cours sera à</p> 
<% elsif @reservations_dates.count >= 2 %>
  <p class="text-center">Vos prochains cours seront à</p> 
<% end %>

  <% @reservations_dates.each do |reservations_date| %>
    <% @index = reservations_date.strftime("%u").to_i %>
     <h3 class="text-center"><%= reservations_date.strftime("%Hh%M- #{@weeks[@index - 1]} %d %m %Y") %><% @reservation = Reservation.find_by(reserved_at: reservations_date) %><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-petit btn-danger btn-xs' %></h3>
  <% end %>
  
<% if params[:week] == '1' || params[:week] == nil  %>
  <%= link_to "Semaine prochaine→" , user_path(week: 2), class: 'right' %>
<% elsif params[:week] == '2' %>
  <%= link_to "←Retourner à cette semaine" , user_path(week: 1)%>
  <%= link_to "Semaine d'après→" , user_path(week: 3), class: 'right' %>
<% elsif params[:week] == '3' %> 
  <%= link_to "←Retourner" , user_path(week: 2)%> 
  <% end %>
  
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="active">#</th>
      <%  (0..6).each do |number| %>
        <%  @index = (@this_monday + number.day).strftime("%u").to_i %>
        <th class="active"><%= (@this_monday + number.day).strftime("#{@weeks[@index - 1]} %d %m %Y") %></th>
      <% end %>
    </tr>  
  </thead>
  <tbody>
    <% count = @reservations_dates.count %>
    <tr> 
      <th>10h00-11h00</th>
        <% (0..6).each do |number| %>
        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day } %>
            <th><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>
    </tr>
    <tr>
      <th class="success">11h15-12h15</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes } %>            
        <th class="success"><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th class="success"><p>-</p></th>
          <% end %>
        <% end %>

    </tr>
    <tr>
      <th>12h30-13h30</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes * 2 } %>            
            <th><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>

    </tr>
    <tr>
      <th class="info">13h45-14h45</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes * 3 } %>            
            <th class="info"><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th class="info"><p>-</p></th>
          <% end %>
        <% end %>

    </tr>
    <tr>
      <th>15h00-16h00</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes * 4 } %>            
            <th><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>

    </tr> 
    <tr>
      <th class="warning">16h15-17h15</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes * 5 } %>            
            <th class="warning"><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th class="warning"><p>-</p></th>
          <% end %>
        <% end %>
  
    </tr>    
    <tr>
      <th>17h30-18h30</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes * 6 } %>            
            <th><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>
    
    </tr>    
    <tr>
      <th class="danger">18h45-19h45</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates[0..(count-1)].find{ |v| v == @your_lesson + number.day + 75.minutes * 7 } %>            
            <th class="danger"><p>Votre cours</p><%= link_to 'Annuler', reservation_path(@reservation), method: :delete, data: { confirm: "Etes-vous sûr?" }, class: 'btn btn-danger btn-xs' %></th>
          <% else %>
            <th class="danger"><p>-</p></th>
          <% end %>
        <% end %>
           
    </tr>        
  </tbody>
</table>  