config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'reservation/valider', to: 'reservations#valider'
  get 'reservation/confirm', to: 'reservations#create'
  get 'reservations/check', to: 'reservations#show'
  post 'reservations/check', to: 'reservations#show'

  get 'inquiry', to: 'inquiries#new'
  resources :users
  resources :reservations
  resources :inquiries
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  
  belongs_to :user
  
 # def available?
  #  Reservation.where(:user_id => @user.id, :reserved_at => @reservation.id).exists?
  #end
  
    def not_available
    unless @reservation.where(:reserved_at => nil)
      return true
    else
      return false
    end
  end
  
  validate :day_quota, :on => :create 
  validate :week_quota, :on => :create 


  private 
    def day_quota
      unless self.user.admin == true
        if self.user.reservations.count >= 1 && self.user.reservations.where(:reserved_at => self.reserved_at.beginning_of_day..self.reserved_at.end_of_day).exists?
          errors.add(:base, "Vous pouvez réserver un cours par jour, vous avez déjà un cours réservé à ce jour-là.")
        end
      end    
    end

    def week_quota
      unless self.user.admin == true
        if self.user.reservations.count >= 2 && self.user.reservations.where(:reserved_at => self.reserved_at.beginning_of_week..self.reserved_at.end_of_week).count > 1
          errors.add(:base, "Vous pouvez réserver deux cours par semaine, vous avez déjà réservé deux cours à cette semaine.")
        end
      end         
    end
      #elsif self.user.reservations.count >= 2 && self.user.reservations.where(:reserved_at => self.reserved_at.beginning_of_day..self.reserved_at.end_of_day + 7.days).exists?
       # errors.add(:base, "Vous avez déjà réservé deux cours à cette semaine.")
      #end         
      #if user.reservations 
       # if user.reservations.count >= 1 && user.reservations.this_day.exists?
        #   
      #  elsif user.reservations.count >= 2 && user.reservations.this_week.exists?
       #   errors.add(:base, "Vous pouvez réserver deux cours par semaine.")
      #  end
      #end
    #end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  require 'date' 
  require 'active_support/all'
  
  def index
      @weeks = ["lun","mar","mer","jeu","ven","sam","dim"]
      @today = Date.current
      @this_monday = @today - (@today.wday - 1)
      reservations = current_user.reservations.map(&:reserved_at)
      reservations.each do |reservation|
        @reservation = Time.new(reservation.year, reservation.month, reservation.day)
      end 
      if (params[:week] == '1') || (params[:week] == nil)
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      
      elsif params[:week] == '2'
        @this_monday += 7.days
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      
      else
        @this_monday += 14.days
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
    end
    
   

  end

  def show
      @weeks = ["lun","mar","mer","jeu","ven","sam","dim"]
      @today = Date.current
      @this_monday = @today - (@today.wday - 1)    
      if (params[:week] == '1') || (params[:week] == nil)
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      
      elsif params[:week] == '2'
        @this_monday += 7.days
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      
      else
        @this_monday += 14.days
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      end
      @reservations = Reservation.all.order('reserved_at ASC')
    @reservations_dates = Reservation.all.order('reserved_at ASC').map(&:reserved_at)
  end
  
  def new
    @reservation = Resesrvation.new
    #@user = User.new
  end

  def create

  
    #@reservation = current_user.reservations.build(reserved_at: params[:reserved_at])
    
      @weeks = ["lun","mar","mer","jeu","ven","sam","dim"]
      @today = Date.current
      @this_monday = @today - (@today.wday - 1)
      reservations = current_user.reservations.map(&:reserved_at)
      reservations.each do |reservation|
        @reservation = Time.new(reservation.year, reservation.month, reservation.day)
      end 
      if (params[:week] == '1') || (params[:week] == nil)
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      
      elsif params[:week] == '2'
        @this_monday += 7.days
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      
      else
        @this_monday += 14.days
        @next_lesson = Time.mktime(@this_monday.year, @this_monday.month, @this_monday.day, 10, 00).in_time_zone("Paris")
      end
    @reservation = current_user.book(params[:reserved_at])
    if @reservation.save 
      flash[:success] = 'Votre cours a été réservé. Je vous enverrai un mail de confirmation sous 24 heures.'
      redirect_to current_user
    else
      render 'index'
      #flash[:danger] = 'Vous pouvez réserver un cours par jour, deux cours par semaine.'
    end 
  end
  

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:success] = 'Votre réservation a été annulé.'
    redirect_back(fallback_location: root_path)
  end

end

app/views/reservations/index.html.erb
<h1 class="text-center">Réservations</h1>
<p class="text-center">Choisissez un horaire et cliquez</p>
<% if action_name == "create" && @reservation.errors.any?  %>
  <div class="alert alert-warning">
    <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<table class="table table-bordered">

  
<% if params[:week] == '1' || params[:week] == nil  %>
  <%= link_to "Semaine prochaine→" , reservations_path(week: 2), class: 'right' %>

<% elsif params[:week] == '2' %>
  <%= link_to "←Retourner à cette semaine" , reservations_path(week: 1)%>
  <%= link_to "Semaine d'après→" , reservations_path(week: 3), class: 'right' %>

<% elsif params[:week] == '3' %> 
  <%= link_to "←Retourner" , reservations_path(week: 2)%> 

<% end %>
  <thead>
    <tr>
      <th class="active">#</th>
      <%  (0..6).each do |number| %>
        <%  @index = (@this_monday + number.day).strftime("%u").to_i %>
        <th class="active"><%= (@this_monday + number.day).strftime("#{@weeks[@index - 1]} %d %m %Y") %></th>
      <% end %>
    </tr>  
  </thead>
  <tbody>
    <tr>
      <th>10h00-11h00</th>
      <%  (0..6).each do |number| %>
        <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day).exists? %>
          <th><%= '×' %></th>
        <% else %>  
          <th><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day) %></th>
        <% end %>
      <% end %>
    </tr>
    <tr>
      <th class="success">11h15-12h15</th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 1).exists? %>
        <th class="success"><%= '×' %></th>
      <% else %>  
        <th class="success"><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes) %></th>
      <% end %>
      <% end %> 
    </tr>
    <tr>
      <th>
        12h30-13h30
      </th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 2).exists? %>
        <th><%= '×' %></th>
      <% else %>        
        <th><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes * 2) %></th>
      <% end %>
      <% end %> 
    </tr>
    <tr>
      <th class="info">
        13h45-14h45
      </th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 3).exists? %>
        <th class="info"><%= '×' %></th>
      <% else %>        
        <th class="info"><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes * 3) %></th>
      <% end %>    
      <% end %> 
    </tr>
    <tr>
      <th>
        15h00-16h00
      </th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 4).exists? %>
        <th><%= '×' %></th>
      <% else %>        
        <th class><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes * 4) %></th>
      <% end %>   
      <% end %> 
    </tr> 
    <tr>
      <th class="warning">
        16h15-17h15
      </th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 5).exists? %>
        <th class="warning"><%= '×' %></th>
      <% else %>        
        <th class="warning"><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes * 5) %></th>
      <% end %>  
      <% end %> 
    </tr>    
    <tr>
      <th>
        17h30-18h30
      </th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 6).exists? %>
        <th><%= '×' %></th>
      <% else %>        
        <th><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes * 6) %></th>
      <% end %>       
      <% end %> 
    </tr>    
    <tr>
      <th class="danger">
        18h45-19h45
      </th>
      <%  (0..6).each do |number| %>
      <% if (@this_monday + number.day) <= @today || Reservation.where(reserved_at: @next_lesson + number.day + 75.minutes * 7).exists? %>
        <th class="danger"><%= '×' %></th>
      <% else %>        
        <th class="danger"><%= link_to '◯', reservation_confirm_path(reserved_at: @next_lesson + number.day + 75.minutes * 7) %></th>
      <% end %>   
      <% end %> 
    </tr>        
  </tbody>
</table>

app/views/reservations/show.html.erb
<h1 class="text-center">Toutes les reservations</h1>
<p>Find me in app/views/reservations/show.html.erb</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>user.id</th>
      <th>name</th>
      <th>email</th>
      <th>time</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.id %></td>
        <td><%= reservation.user.id %></td>
        <td><%= reservation.user.name %></td>
        <td><%= reservation.user.email %></td>
        <td><%= reservation.reserved_at %></td>
      </tr>
    <% end %>  
  </tbody>
</table>

<% if params[:week] == '1' || params[:week] == nil  %>
  <%= link_to "Semaine prochaine→" , reservations_check_path(week: 2), class: 'right' %>
<% elsif params[:week] == '2' %>
  <%= link_to "←Retourner à cette semaine" , reservations_check_path(week: 1)%>
  <%= link_to "Semaine d'après→" , reservations_check_path(week: 3), class: 'right' %>
<% elsif params[:week] == '3' %> 
  <%= link_to "←Retourner" , reservations_check_path(week: 2)%> 
  <% end %>
  
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="active">#</th>
      <%  (0..6).each do |number| %>
        <%  @index = (@this_monday + number.day).strftime("%u").to_i %>
        <th class="active"><%= (@this_monday + number.day).strftime("#{@weeks[@index - 1]} %d %m %Y") %></th>
      <% end %>
    </tr>  
  </thead>
  <tbody>
   
    <tr> 
      <th>10h00-11h00</th>
        <% (0..6).each do |number| %>
        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day } %>
            <th><p>pris</p></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>
    </tr>
    <tr>
      <th class="success">11h15-12h15</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes } %>            
        <th class="success"><p>pris</p></th>
          <% else %>
            <th class="success"><p>-</p></th>
          <% end %>
        <% end %>

    </tr>
    <tr>
      <th>12h30-13h30</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes * 2 } %>            
            <th><p>pris</p></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>

    </tr>
    <tr>
      <th class="info">13h45-14h45</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes * 3 } %>            
            <th class="info"><p>pris</p></th>
          <% else %>
            <th class="info"><p>-</p></th>
          <% end %>
        <% end %>

    </tr>
    <tr>
      <th>15h00-16h00</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes * 4 } %>            
            <th><p>pris</p></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>

    </tr> 
    <tr>
      <th class="warning">16h15-17h15</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes * 5 } %>            
            <th class="warning"><p>pris</p></th>
          <% else %>
            <th class="warning"><p>-</p></th>
          <% end %>
        <% end %>
  
    </tr>    
    <tr>
      <th>17h30-18h30</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes * 6 } %>            
            <th><p>pris</p></th>
          <% else %>
            <th><p>-</p></th>
          <% end %>
        <% end %>
    
    </tr>    
    <tr>
      <th class="danger">18h45-19h45</th>
      <% (0..6).each do |number| %>

        <% if @reservations_dates.find{ |v| v == @next_lesson + number.day + 75.minutes * 7 } %>            
            <th class="danger"><p>pris</p></th>
          <% else %>
            <th class="danger"><p>-</p></th>
          <% end %>
        <% end %>
           
    </tr>        
  </tbody>
</table>  