config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'reservation/valider', to: 'reservations#valider'
  get 'reservation/confirm', to: 'reservations#create'
  get 'reservations/check', to: 'reservations#show'
  post 'reservations/check', to: 'reservations#show'

  get 'inquiry', to: 'inquiries#new'
  resources :users
  resources :reservations
  resources :inquiries
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>  

app/views/layouts/_footer.html.erb
<footer class="page-footer special-color-dark pt-4">
  <div class="text-center text-muted">
    ©KotoFranceJapon.
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
         <span class="sr-only">Toggle Navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">KotoFranceJapon</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
    
            <% if current_user.try(:admin?) %>
              <li><%= link_to 'Boîte messages', inquiries_path %></li>
              <li><%= link_to 'Réservations', reservations_check_path %></li>
            <% end %>  
              <li><%= link_to 'Réserver un cours', reservations_path %></li>
            <% if logged_in? %>
              <li><%= link_to 'Mon espace', user_path(current_user) %></li>
            <% end %>                
              <li><%= link_to 'Contact', inquiry_path %></li>

            <% if logged_in? %>              
              <li><%= link_to 'Déconnexion', logout_path, method: :delete %></li>
            <% else %>  
              <li><%= link_to "S'inscrire", signup_path %></li>
              <li><%= link_to 'Se connecter', login_path %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <title>KotoFranceJapon</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>